### ISSUE TITLE
Beta version in docker

### ISSUE THREAD

**Issue by rob1981forest** [lucacalcaterra/risco-mqtt-bridge#18]
Hi,
I have the main release running fine in docker for a while now - thanks a lot !

Is there anyway I can use the beta version in docker ? I run Hass in docker on a synology and would like to mess about with the detectors and event log integration the beta release has....

Thanks a lot

**Comment by pergolafabio** [comment]
Yeah , wanna know this too, I want also event integration and want to see
how that autodiscovery works

Op wo 26 jun. 2019 19:25 schreef rob1981forest <notifications@github.com>:

**Comment by pergolafabio** [comment]
for testing i created sensors like below , but the state is always unknown :)
```
sensor:
  - platform: mqtt
    state_topic: "riscopanel/eventhistory"
    name: risco_event
    
  - platform: mqtt
    state_topic: "riscopanel/dects"
    name: risco_dects
```
